"""Worker implementing the anomaly recheck and AI reasoning alert pipeline.

Per Section 2 and Section 5 of AGENTS.md:
1. PATROL / SENSE -> detect_anomaly -> IF True -> Create Anomaly(status=PENDING) and
   transition state machine to RECHECKING (no immediate alert).
2. On next reading from same room (RECHECK):
   - If anomaly still present: Mark Anomaly(status=CONFIRMED), compute severity,
     call reasoning_agent.explain_anomaly, create Alert(status=active).
   - If reading is normal: Mark Anomaly(status=RESOLVED, resolved_at=now), NO alert.
"""

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from sqlalchemy import desc, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.reasoning_agent import explain_anomaly_async
from app.core.db import async_session_factory
from app.core.logging import logger
from app.models.alert import Alert, Anomaly
from app.robotics.state_machine import RobotState
from app.services.anomaly_service import (
    detect_anomaly,
    evaluate_reading_anomalies,
    get_metric_severity,
)
from app.services.dashboard_broadcaster import broadcast_alert
from app.services.robot_service import get_state_machine
from app.services.room_service import RoomService

# In-memory registry for active pending recheck tracking
_pending_anomalies: Dict[str, Dict[str, Any]] = {}
_worker_created_alerts: List[Dict[str, Any]] = []


def get_pending_anomalies() -> Dict[str, Dict[str, Any]]:
    """Return in-memory dictionary of rooms currently in pending recheck state."""
    return _pending_anomalies


def get_created_alerts() -> List[Dict[str, Any]]:
    """Return all alerts generated by the anomaly worker."""
    return _worker_created_alerts


def reset_worker_state() -> None:
    """Reset worker in-memory tracking (useful between test runs)."""
    _pending_anomalies.clear()
    _worker_created_alerts.clear()


class AnomalyWorker:
    """Worker managing the 2-step anomaly confirmation and alert reasoning lifecycle."""

    @staticmethod
    async def process_reading(
        reading: Dict[str, Any],
        db: Optional[AsyncSession] = None,
    ) -> Dict[str, Any]:
        """Process incoming sensor reading through the recheck confirmation pipeline.

        Args:
            reading: Dictionary with sensor readings (room_id, temperature, humidity, sound_level).
            db: Optional async database session.

        Returns:
            Dictionary detailing the pipeline action taken and any generated anomalies/alerts.
        """
        room_id = reading.get("room_id")
        if not room_id:
            return {"action": "SKIPPED_NO_ROOM", "room_id": None}

        # 1. Fetch Room Baseline
        room_info = await RoomService.get_room(room_id, db=db)
        if not room_info or not room_info.get("baseline"):
            return {"action": "SKIPPED_NO_BASELINE", "room_id": room_id}

        baseline = room_info["baseline"]
        sm = get_state_machine()
        now = datetime.now(timezone.utc)
        reading_id = reading.get("id") or f"sr_{uuid.uuid4().hex[:8]}"

        # Check if there is already a PENDING anomaly for this room
        pending = _pending_anomalies.get(room_id)

        # -------------------------------------------------------------
        # Scenario A: RECHECK STEP (Room was already in PENDING state)
        # -------------------------------------------------------------
        if pending is not None:
            is_anomaly, anomaly_types = detect_anomaly(reading, baseline)

            if is_anomaly:
                # Anomaly is STILL PRESENT -> CONFIRM ANOMALY AND GENERATE ALERT
                anomaly_id = pending["id"]
                pending["status"] = "CONFIRMED"
                pending["confirmed_at"] = now.isoformat()

                # Evaluate detailed metric info and calculate severity
                evaluations = evaluate_reading_anomalies(reading, baseline)
                top_eval = evaluations[0] if evaluations else {
                    "type": anomaly_types[0],
                    "severity": "HIGH",
                    "value": reading.get("temperature", 0.0),
                    "expected_min": baseline.get("temperature_min"),
                    "expected_max": baseline.get("temperature_max"),
                }
                severity = top_eval["severity"]

                # Generate AI reasoning plain-language explanation
                ai_context = {
                    "room_id": room_id,
                    "room_name": room_info.get("name", room_id),
                    "type": top_eval["type"],
                    "value": top_eval["value"],
                    "expected_min": top_eval.get("expected_min"),
                    "expected_max": top_eval.get("expected_max"),
                    "severity": severity,
                    "trend": "Confirmed upon automated recheck inspection.",
                }

                try:
                    message_text = await explain_anomaly_async(ai_context)
                except Exception as e:
                    logger.warning("AI explanation failed, using deterministic template: %s", e)
                    message_text = (
                        f"Confirmed {top_eval['type']} in {room_info.get('name', room_id)}: "
                        f"Value {top_eval['value']} outside safe bounds. Severity: {severity}."
                    )

                # Create Alert record
                alert_id = f"alert_{uuid.uuid4().hex[:8]}"
                alert_data = {
                    "id": alert_id,
                    "anomaly_id": anomaly_id,
                    "room_id": room_id,
                    "severity": severity,
                    "message": message_text,
                    "channel": "dashboard",
                    "status": "active",
                    "created_at": now.isoformat(),
                    "acknowledged_at": None,
                }
                _worker_created_alerts.append(alert_data)

                # Broadcast live alert to all connected dashboard WebSocket clients
                await broadcast_alert(alert_data)

                # Persist confirmed anomaly and alert to database if session exists
                if db is not None:
                    try:
                        res = await db.execute(select(Anomaly).where(Anomaly.id == anomaly_id))
                        db_anom = res.scalars().first()
                        if db_anom:
                            db_anom.status = "CONFIRMED"
                            db_anom.severity = severity

                        db_alert = Alert(
                            id=alert_id,
                            anomaly_id=anomaly_id,
                            room_id=room_id,
                            severity=severity,
                            message=message_text,
                            channel="dashboard",
                            status="active",
                            created_at=now,
                        )
                        db.add(db_alert)
                        await db.commit()
                    except Exception as e:
                        logger.debug("Database alert persistence deferred: %s", e)

                # Restore state machine from RECHECKING
                if sm.state == RobotState.RECHECKING:
                    sm.transition_to(RobotState.IDLE)

                del _pending_anomalies[room_id]

                return {
                    "action": "CONFIRMED_AND_ALERTED",
                    "anomaly_id": anomaly_id,
                    "alert": alert_data,
                    "status": "CONFIRMED",
                }

            else:
                # Recheck reading is NOW NORMAL -> RESOLVE WITHOUT ALERTING
                anomaly_id = pending["id"]
                pending["status"] = "RESOLVED"
                pending["resolved_at"] = now.isoformat()

                if db is not None:
                    try:
                        res = await db.execute(select(Anomaly).where(Anomaly.id == anomaly_id))
                        db_anom = res.scalars().first()
                        if db_anom:
                            db_anom.status = "RESOLVED"
                            db_anom.resolved_at = now
                            await db.commit()
                    except Exception as e:
                        logger.debug("Database anomaly resolution deferred: %s", e)

                # Restore state machine from RECHECKING
                if sm.state == RobotState.RECHECKING:
                    sm.transition_to(RobotState.IDLE)

                del _pending_anomalies[room_id]

                return {
                    "action": "RESOLVED_NO_ALERT",
                    "anomaly_id": anomaly_id,
                    "status": "RESOLVED",
                }

        # -------------------------------------------------------------
        # Scenario B: FIRST OBSERVATION (Check if anomaly triggers PENDING)
        # -------------------------------------------------------------
        is_anomaly, anomaly_types = detect_anomaly(reading, baseline)

        if is_anomaly:
            evaluations = evaluate_reading_anomalies(reading, baseline)
            top_eval = evaluations[0] if evaluations else {
                "type": anomaly_types[0],
                "severity": "MEDIUM",
                "value": reading.get("temperature", 0.0),
                "expected_min": baseline.get("temperature_min"),
                "expected_max": baseline.get("temperature_max"),
            }

            anomaly_id = f"anom_{uuid.uuid4().hex[:8]}"
            pending_anomaly = {
                "id": anomaly_id,
                "room_id": room_id,
                "reading_id": reading_id,
                "type": top_eval["type"],
                "severity": top_eval["severity"],
                "value": top_eval["value"],
                "expected_min": top_eval.get("expected_min"),
                "expected_max": top_eval.get("expected_max"),
                "status": "PENDING",
                "detected_at": now.isoformat(),
                "resolved_at": None,
            }

            _pending_anomalies[room_id] = pending_anomaly

            # Persist pending anomaly to DB
            if db is not None:
                try:
                    db_anom = Anomaly(
                        id=anomaly_id,
                        room_id=room_id,
                        reading_id=reading_id,
                        type=top_eval["type"],
                        severity=top_eval["severity"],
                        value=top_eval["value"],
                        expected_min=top_eval.get("expected_min"),
                        expected_max=top_eval.get("expected_max"),
                        status="PENDING",
                        detected_at=now,
                    )
                    db.add(db_anom)
                    await db.commit()
                except Exception as e:
                    logger.debug("Database pending anomaly persistence deferred: %s", e)

            # Trigger state machine to RECHECKING
            sm.current_room_id = room_id
            if sm.state in (RobotState.IDLE, RobotState.PATROLLING, RobotState.SENSING, RobotState.MOVING):
                sm.transition_to(RobotState.RECHECKING)

            return {
                "action": "PENDING_RECHECK_TRIGGERED",
                "anomaly_id": anomaly_id,
                "status": "PENDING",
                "room_id": room_id,
            }

        return {"action": "NORMAL", "is_anomaly": False}
