; PlatformIO Project Configuration File for SafeRoom ESP32 Rover Firmware
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize

; Compiler Build Flags
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_RUNNING_CORE=1

; External Libraries
lib_deps =
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.4
